### ISSUE TITLE
Provide RTL support

### ISSUE THREAD

**Issue by khawars** [ruslanskorb/RSKPlaceholderTextView#19]
I am creating an app with Arabic language. Placeholder should be RTL, but it is showing on left side.
Typing text displays correctly RTL

**Comment by ruslanskorb** [comment]
Support for RTL layout direction was added in the version [3.1.0](https://github.com/ruslanskorb/RSKPlaceholderTextView/releases/tag/3.1.0). What version of **RSKPlaceholderTextView** are you using?

**Comment by ruslanskorb** [comment]
@khawars Just checked RTL layout direction in the version **5.0.1**. It is working. Please, check the latest version and re-open the issue if the problem still persists.
