### ISSUE TITLE
Using RSKPlaceholderTextView with swift Storyboard

### ISSUE THREAD

**Issue by satyam90** [ruslanskorb/RSKPlaceholderTextView#2]
I added this control in Pods
I'm placing UITextView in storyboard and changed the class to "RSKPlaceholderTextView".

When compiling, its throwing warning that its not able to find the class "RSKPlaceholderTextView" is not found and changing to "UITextView".

When running the app, its crashing while setting placeholder text.

**Comment by ruslanskorb** [comment]
@satyam90 Can you provide a sample project with your problem?

**Comment by lfarah** [comment]
I had the same problem. I get the following error:

> 2016-08-15 02:55:41.735 Bable[98644:10672363] Failed to set (placeholderColor) user defined inspected property on (UITextView): [<UITextView 0x7f884e034000> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key placeholderColor.

**Comment by lfarah** [comment]
<img width="682" alt="screen shot 2016-08-15 at 2 59 35 am" src="https://cloud.githubusercontent.com/assets/6511079/17661484/54adf132-6294-11e6-87d9-38cfcfe3fa6e.png">

**Comment by ruslanskorb** [comment]
You should set the module for your custom class to `RSKPlaceholderTextView`.
Here is [an example project](https://dl.dropboxusercontent.com/u/89891480/RSKPlaceholderTextViewWithCocoapods.zip).

**Comment by lfarah** [comment]
@ruslanskorb now it works perfectly. This instruction could also be in #3
