### ISSUE TITLE
Bug placehoder

### ISSUE THREAD

**Issue by hien352911** [ruslanskorb/RSKPlaceholderTextView#20]
My placeholder is 2 row. Ex: Nhap noi dung nhan xet o day. Toi thieu 50 ki tu. 
When i wrote 2 row and remove all, my placeholder display 1 row.

**Comment by ruslanskorb** [comment]
@hien352911 How do you manage the height of a `RSKPlaceholderTextView`?

**Comment by hien352911** [comment]
I opend sample project on github and it was the same. 
I just change placeholder to 2 rows and don't change anything.

**Comment by ruslanskorb** [comment]
@hien352911 Could you try again with the latest changes from **master**?

**Comment by ruslanskorb** [comment]
@hien352911 Unfortunately I can not reproduce your problem on version **5.0.1**. Could you provide steps for this?

**Comment by hien352911** [comment]
sorry, my problem is RSKGrowingTextView. I posted wrong group.
