### ISSUE TITLE
Growing Text subclass

### ISSUE THREAD

**Issue by neodave** [ruslanskorb/RSKPlaceholderTextView#21]
Can this be combined with your GrowingText TextView class?

**Comment by ruslanskorb** [comment]
@neodave Yes, `RSKGrowingTextView` is a [subclass](https://github.com/ruslanskorb/RSKGrowingTextView/blob/master/RSKGrowingTextView/RSKGrowingTextView.swift#L46) of `RSKPlaceholderTextView`.
