### ISSUE TITLE
Cursor does not respect textContainerInset when it's set

### ISSUE THREAD

**Issue by jackguo709** [ruslanskorb/RSKPlaceholderTextView#24]
When I set textContainerInset of the textView, the cursor does not respect it

**Comment by ruslanskorb** [comment]
@jackguo709 Thanks for reporting! I'll look into it tomorrow morning.

**Comment by ruslanskorb** [comment]
@jackguo709 One question at the moment, does it affect all languages or only RTL?

**Comment by ruslanskorb** [comment]
@jackguo709 Could you check if the changes made in the master branch work for you?

**Comment by ruslanskorb** [comment]
Fixed in version [6.0.3](https://github.com/ruslanskorb/RSKPlaceholderTextView/releases/tag/6.0.3).
