### ISSUE TITLE
Clear text after tap

### ISSUE THREAD

**Issue by fury21** [ruslanskorb/RSKPlaceholderTextView#25]
Hi and thanks for your work!
How to make the placeholder disappear as soon as I place the cursor and the keyboard is shown, and not when I just start typing?

**Comment by ruslanskorb** [comment]
Hi @fury21,

You can set `attributedPlaceholder` / `placeholder` to `nil` in the `textViewDidBeginEditing(_:)` method of `UITextViewDelegate` if `attributedText` / `text` of `UITextView` is empty, and change it back to what it was before in the `textViewDidEndEditing(_:)` method if `attributedText` / `text` is still empty.
