### ISSUE TITLE
Multiline Placeholder Support

### ISSUE THREAD

**Issue by shubham14896** [ruslanskorb/RSKPlaceholderTextView#26]
Issue is 
Multiline placeholder support is available in example project (version - https://github.com/ruslanskorb/RSKPlaceholderTextView/releases/tag/5.0.1)
But when you try with latest version it does not work as expected.

**Comment by ruslanskorb** [comment]
Hi @shubham14896. What do you mean by "it does not work as expected"?

**Comment by shubham14896** [comment]
So try adding multiline placeholder in latest version 

It will not work, output will be the placeholder will be clipped after single line 

And try with version 5.0.1 
The placeholder text will not get clipped even it expands it to multiple lines 


If you want I can submit PR for same

**Comment by ruslanskorb** [comment]
@shubham14896 Which version are you using? I have checked version [6.0.3](https://github.com/ruslanskorb/RSKPlaceholderTextView/releases/tag/6.0.3) on iOS 10.3.1, 11.0.1, 13.6. Everything works for them as expected.
Feel free to open the PR, I'll take a look at it.

**Comment by ruslanskorb** [comment]
@shubham14896 Feel free to reopen the issue if it is still not resolved.
