### ISSUE TITLE
Provide example code in Readme

### ISSUE THREAD

**Issue by lfarah** [ruslanskorb/RSKPlaceholderTextView#3]
Your lib is great.

I'd be cool to show some code on how to use **RSKPlaceholderTextView** instead of me having to open the example app.
You can check [this link](https://github.com/awesome-labs/iOS-readme-template) and [this link](https://github.com/awesome-labs/LFTimePicker) for ideas.

Let me know how I can help!

**Comment by ruslanskorb** [comment]
@lfarah What would you like to see in the section **Usage**?

**Comment by lfarah** [comment]
I'd like to see a very simple code implementation without the Storyboard. What do you think about this?

## Implementation

``` swift
var txtDescription: RSKPlaceHolderTextView?
txtDescription = RSKPlaceholderTextView(frame: CGRect(x: 50, y: 50, width: 100, height: 100))
txtDescription.placeholder = "What do you want to say about this event?"
```

**Comment by ruslanskorb** [comment]
I hope [this](https://github.com/ruslanskorb/RSKPlaceholderTextView/commit/82ce97d67e8011126ef394b34bb8cf8ee4f3448b) will be enough.

**Comment by ruslanskorb** [comment]
@lfarah Thanks for raising the issue!

**Comment by lfarah** [comment]
It's perfect! 🎉
