### ISSUE TITLE
Error in Swift 4.0

### ISSUE THREAD

**Issue by Rastaman72** [ruslanskorb/RSKPlaceholderTextView#6]
Please fix library.
<img width="1401" alt="screen shot 2017-09-26 at 08 47 10" src="https://user-images.githubusercontent.com/7621469/30846293-56df13fc-a297-11e7-8365-71d27c0b6274.png">

I've just updated my pod to current version (RSKPlaceholderTextView (3.0.0)) and got plenty of errors.

**Comment by ruslanskorb** [comment]
Please check your current Swift version in Build Settings.

<img width="1006" alt="screen shot 2017-09-26 at 10 02 48 am" src="https://user-images.githubusercontent.com/1182823/30847078-dbf4f772-a2a2-11e7-8b49-5c0f019db964.png">

[Placeholder-Swift-4.zip](https://github.com/ruslanskorb/RSKPlaceholderTextView/files/1332116/Placeholder-Swift-4.zip)

**Comment by ruslanskorb** [comment]
@Rastaman72 Did you solve your problem?

**Comment by sasojadrovski** [comment]
Hey @ruslanskorb,

I am facing the same issue, but I know what's the problem in my case (might be the same for @Rastaman72). 
I am using your `RSKGrowingTextView` library, which has this library as a dependency, and since the `RSKGrowingTextView` has not been updated, the `.podspec` file points to an earlier version of `RSKPlaceholderTextView`, thus the latest version never gets installed.

Could you please update the `RSKGrowingTextView` library as well?

Thanks!

**Comment by ruslanskorb** [comment]
Hi @sasojadrovski,

Thanks for the info! I've updated [RSKGrowingTextView](https://github.com/ruslanskorb/RSKGrowingTextView/releases/tag/3.0.0) for Swift 4.0. Can you check it and let me know if the problem still persists?

**Comment by sasojadrovski** [comment]
Hi @ruslanskorb,

You are welcome 😊 Yes, I will check it out later today and let you know the outcome.

Thank you for looking into this so promptly. I appreciate it!

Cheers,
Sasho

**Comment by sasojadrovski** [comment]
Hey @ruslanskorb,

I have just checked and the issue is resolved! Thank you once again.

Cheers,
Sasho

**Comment by ruslanskorb** [comment]
Hey @sasojadrovski,

Glad to hear it!
Thank you for your help! I really appreciate it! :thumbsup: 

Cheers,
Ruslan

**Comment by mansishah278** [comment]
@ruslanskorb I have the same issue for swift 3.2
Plenty of errors have shown up

**Comment by anraag** [comment]
@ruslanskorb , I am facing the same issue as @Rastaman72 . 12 issues have shown up and my swift version in build settings is 4.0. Please help

**Comment by ruslanskorb** [comment]
@anraag Check the version of `RSKPlaceholderTextView` that you are using. This should be version [3.0.0](https://github.com/ruslanskorb/RSKPlaceholderTextView/releases/tag/3.0.0). Probably, you need to run `pod update RSKPlaceholderTextView` from the command line.

**Comment by anraag** [comment]
I updated it. Same issues

**Comment by ruslanskorb** [comment]
@anraag Provide a sample project with your issue. Then, maybe, I will be able to help you.

p.s. have a look on [this sample project](https://github.com/ruslanskorb/RSKPlaceholderTextView/files/1332116/Placeholder-Swift-4.zip), It uses Swift 4 and everything works without any errors.

**Comment by anraag** [comment]
https://github.com/anraag/Anurag-s-Twitter

**Comment by ruslanskorb** [comment]
@anraag Your `RSKPlaceholderTextView` target uses Swift 3.2.

<img width="868" alt="screen shot 2018-03-25 at 21 18 40" src="https://user-images.githubusercontent.com/1182823/37878437-2246b744-3072-11e8-995f-e7ddb6d80664.png">

Change it to Swift 4. And errors will disappear.

**Comment by anraag** [comment]
Thanks. My bad. It solved the issue.
