### ISSUE TITLE
textField.returnKeyType = .next  无效

### ISSUE THREAD

**Issue by PhoenixLeeSin** [ruslanskorb/RSKPlaceholderTextView#8]
lazy var steward_2Body:RSKPlaceholderTextView = {
        let textField = RSKPlaceholderTextView()
        textField.font = UIFont.systemFont(ofSize: 14)
        textField.layer.borderWidth = 1
        textField.layer.borderColor = UIColor.black.cgColor
        textField.returnKeyType = .next
        return textField
    }()
textField.returnKeyType = .next  这句话无效。。。。。

**Comment by ruslanskorb** [comment]
@350541732 I checked your code, it works. I need more information. What versions of Xcode and Swift are you using?

**Comment by PhoenixLeeSin** [comment]
@ruslanskorb  sorry i find it is my error thanks a lot
