### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by cnzlh** [ruslanskorb/RSKPlaceholderTextView#9]
![image](https://user-images.githubusercontent.com/5771860/39634600-cdee0a30-4fed-11e8-9c7f-2e84cedf0902.png)
my Xcode version is 9.3

**Comment by ruslanskorb** [comment]
Hi, @cnzlh!

How do you install **RSKPlaceholderTextView**? (Carthage or Cocoapods)

The following command might resolve the problem:

```sh
rm -rf ~/Library/Developer/Xcode/DerivedData
```

**Comment by cnzlh** [comment]
Thanks for response. I am using your library through Cocoapods, I just try to clean the project, but no effect. But I delete the textView in storyboard and add it again. the error disappeared. howerver this error reappeared sometimes.

**Comment by ruslanskorb** [comment]
Thanks for the info! Looks like an Xcode problem. It's good to hear that you found a solution to this problem. I'll close the issue for now. If you have any other information, feel free to reopen it.
